version: "3"

services:

  api:
    container_name: barmanager
    restart: always
    image: bmg:1
    env_file:
      - .env
    ports:
      - "3000:3000"
    # depends_on:
    #   - db-production

  # db-production:
  #   container_name: prod-db-bmg
  #   restart: always
  #   image: postgres:15.1
  #   volumes:
  #     - db-production:/var/lib/postgresql/data
  #   ports:
  #     - "5438:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}         
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}

  db-development:
    container_name: dev_db_bmg
    restart: always
    image: postgres:15.1
    volumes:
      - db-development-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: dev_barmanager        
      POSTGRES_PASSWORD: ditbmg

  db-testing:
    container_name: test_db_bmg
    restart: always
    image: postgres:15.1
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: test_barmanager       
      POSTGRES_PASSWORD: testditbmg
    volumes:
      - db-testing-data:/var/lib/postgresql/data

volumes:
  # db-production:
  #   external: false
  db-development-data:
    external: false
  db-testing-data:
    external: false
